# Generated by Django 6.1 on 2026-08-25 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills, e.g. Python, UI design, Django', max_length=255)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(choices=[('weekends', 'Weekends'), ('evenings', 'Evenings'), ('full_time', 'Full-time'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('looking_for', models.TextField(blank=True, help_text='Describe the project, teammates, or role you want. Used later for AI matching.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
